sudo: false
language: node_js
node_js:
<<<<<<< HEAD
  - "node"
=======
- "node"
>>>>>>> 課題B提出
dist: trusty
addons:
  chrome: stable
  firefox: latest
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mislav.marohnic@gmail.com
  api_key:
    secure: gt9g5/bXhxSKjxfFSPCdpWGJKBrSG8zdGRYgPouUgRqNeD2Ff4Nc8HGQTxp0OLKnP/jJ5FIru5jUur6LWzJCyEd+aNUEvFf5J078m3pzHN9AP2fiWUkKXcc5lKV0PQnI+JDRxJwd/PggtjubrneGfCzyFoys9apRrd/TzTGEtGw=
  on:
    tags: true
<<<<<<< HEAD
    repo: github/fetch
=======
    repo: github/fetch
>>>>>>> 課題B提出
